"""
Django settings for zinnia2 project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_URL = '/static/'
STATIC_ROOT = 'home/'
MEDIA_ROOT = 'media'
MEDIA_URL = '/media/'



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q**dd@eg6juh*!b)1h$-1qz7zwn1dqk!xbc--!p5g0#s=tg7is'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
    'django.contrib.sitemaps',
    'django_comments',
    'mptt',
    'tagging',
    'zinnia',
    'zinniablog2',
    'multiselectfield',
    'contacto',
    'simple_history',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'zinnia2.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'templates')],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.contrib.auth.context_processors.auth',
        'django.template.context_processors.i18n',
        'django.template.context_processors.request',
        'django.contrib.messages.context_processors.messages',
        'zinnia.context_processors.version',  # Optional
      ]
    }
  }
]

WSGI_APPLICATION = 'zinnia2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/



SITE_ID = 1


'''
Servers:

POP (for receiving) — mail.webfaction.com
IMAP (for receiving) — mail.webfaction.com
SMTP (for sending) — smtp.webfaction.com
Ports:

 	Standard	Secure (SSL)	Secure (TLS)
POP	110	995
IMAP	143	993
SMTP	25	465	587
Servers:

POP (for receiving) — mail.webfaction.com
IMAP (for receiving) — mail.webfaction.com
SMTP (for sending) — smtp.webfaction.com
Ports:

 	Standard	Secure (SSL)	Secure (TLS)
POP 	110     	995
IMAP	143     	993
SMTP	25	        465	            587
'''
ADMINS = (('Scort', 'scort@divinasur.cl'))
WEBFACTION = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

if WEBFACTION is True:
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST = 'smtp.webfaction.com'
    EMAIL_HOST_USER = 'scort_divinasur'
    EMAIL_HOST_PASSWORD = 'superandres1'
    # EMAIL_SSL_KEYFILE = None
    DEFAULT_FROM_EMAIL = 'scort@divinasur.cl'
    # SERVER_EMAIL = 'scort@divinasur.cl'
    # DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

else:
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_HOST_USER = 'ainsworth.developed@gmail.com'
    EMAIL_HOST_PASSWORD = 'Googledemierda4000'
